/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/evals/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Review Jobs */
        get: operations["read_review_jobs_api_v1_evals_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evals/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace Job Evaluation */
        put: operations["replace_job_evaluation_api_v1_evals_jobs__job_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evals/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Eval Report */
        get: operations["read_eval_report_api_v1_evals_report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Jobs */
        get: operations["read_jobs_api_v1_jobs_get"];
        put?: never;
        /** Create Job */
        post: operations["create_job_api_v1_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Job */
        get: operations["read_job_api_v1_jobs__job_id__get"];
        /** Replace Job */
        put: operations["replace_job_api_v1_jobs__job_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Job Match */
        get: operations["read_job_match_api_v1_jobs__job_id__match_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Profile */
        get: operations["read_profile_api_v1_profile_get"];
        /** Upsert Profile */
        put: operations["upsert_profile_api_v1_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["liveness_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CandidateFactInput */
        CandidateFactInput: {
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
            kind: components["schemas"]["FactKind"];
            /** Source Ref */
            source_ref?: string | null;
            /** @default USER_CONFIRMED */
            source_type: components["schemas"]["FactSource"];
            /** Value */
            value: string;
        };
        /** CandidateFactResponse */
        CandidateFactResponse: {
            /** Confidence */
            confidence: number;
            /** Confirmed At */
            confirmed_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["FactKind"];
            /** Source Ref */
            source_ref: string | null;
            source_type: components["schemas"]["FactSource"];
            /** Value */
            value: string;
        };
        /** CandidateProfileResponse */
        CandidateProfileResponse: {
            /** Certifications */
            certifications: components["schemas"]["CertificationResponse"][];
            /** City */
            city: string | null;
            /** Country Code */
            country_code: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Education */
            education: components["schemas"]["EducationResponse"][];
            /** Email */
            email: string | null;
            /** Experiences */
            experiences: components["schemas"]["ExperienceResponse"][];
            /** Facts */
            facts: components["schemas"]["CandidateFactResponse"][];
            /** Full Name */
            full_name: string;
            /** Github Url */
            github_url: string | null;
            /** Headline */
            headline: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Languages */
            languages: components["schemas"]["LanguageResponse"][];
            /** Linkedin Url */
            linkedin_url: string | null;
            /** Phone */
            phone: string | null;
            /** Portfolio Url */
            portfolio_url: string | null;
            preferences: components["schemas"]["CareerPreferenceResponse"];
            /** Professional Summary */
            professional_summary: string | null;
            /** Skills */
            skills: components["schemas"]["SkillResponse"][];
            /** State */
            state: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CandidateProfileUpsert */
        CandidateProfileUpsert: {
            /** Certifications */
            certifications?: components["schemas"]["CertificationInput"][];
            /** City */
            city?: string | null;
            /**
             * Country Code
             * @default BR
             */
            country_code: string;
            /** Education */
            education?: components["schemas"]["EducationInput"][];
            /** Email */
            email?: string | null;
            /** Experiences */
            experiences?: components["schemas"]["ExperienceInput"][];
            /** Facts */
            facts?: components["schemas"]["CandidateFactInput"][];
            /** Full Name */
            full_name: string;
            /** Github Url */
            github_url?: string | null;
            /** Headline */
            headline?: string | null;
            /** Languages */
            languages?: components["schemas"]["LanguageInput"][];
            /** Linkedin Url */
            linkedin_url?: string | null;
            /** Phone */
            phone?: string | null;
            /** Portfolio Url */
            portfolio_url?: string | null;
            preferences?: components["schemas"]["CareerPreferenceInput"];
            /** Professional Summary */
            professional_summary?: string | null;
            /** Skills */
            skills?: components["schemas"]["SkillInput"][];
            /** State */
            state?: string | null;
        };
        /** CareerPreferenceInput */
        CareerPreferenceInput: {
            /** Contract Types */
            contract_types?: components["schemas"]["ContractType"][];
            /** Desired Areas */
            desired_areas?: string[];
            /** Desired Titles */
            desired_titles?: string[];
            /**
             * Salary Currency
             * @default BRL
             */
            salary_currency: string;
            /** Salary Max */
            salary_max?: number | null;
            /** Salary Min */
            salary_min?: number | null;
            /** Seniority Levels */
            seniority_levels?: components["schemas"]["Seniority"][];
            /** Target Locations */
            target_locations?: string[];
            /**
             * Willing To Relocate
             * @default false
             */
            willing_to_relocate: boolean;
            /**
             * Willing To Travel
             * @default false
             */
            willing_to_travel: boolean;
            /** Work Models */
            work_models?: components["schemas"]["WorkModel"][];
        };
        /** CareerPreferenceResponse */
        CareerPreferenceResponse: {
            /** Contract Types */
            contract_types: components["schemas"]["ContractType"][];
            /** Desired Areas */
            desired_areas: string[];
            /** Desired Titles */
            desired_titles: string[];
            /** Salary Currency */
            salary_currency: string;
            /** Salary Max */
            salary_max: number | null;
            /** Salary Min */
            salary_min: number | null;
            /** Seniority Levels */
            seniority_levels: components["schemas"]["Seniority"][];
            /** Target Locations */
            target_locations: string[];
            /** Willing To Relocate */
            willing_to_relocate: boolean;
            /** Willing To Travel */
            willing_to_travel: boolean;
            /** Work Models */
            work_models: components["schemas"]["WorkModel"][];
        };
        /** CertificationInput */
        CertificationInput: {
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
            /** Credential Url */
            credential_url?: string | null;
            /** Expires Date */
            expires_date?: string | null;
            /** Issued Date */
            issued_date?: string | null;
            /** Issuer */
            issuer?: string | null;
            /** Name */
            name: string;
            /** Source Ref */
            source_ref?: string | null;
            /** @default USER_CONFIRMED */
            source_type: components["schemas"]["FactSource"];
        };
        /** CertificationResponse */
        CertificationResponse: {
            /** Confidence */
            confidence: number;
            /** Confirmed At */
            confirmed_at: string | null;
            /** Credential Url */
            credential_url: string | null;
            /** Expires Date */
            expires_date: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Issued Date */
            issued_date: string | null;
            /** Issuer */
            issuer: string | null;
            /** Name */
            name: string;
            /** Source Ref */
            source_ref: string | null;
            source_type: components["schemas"]["FactSource"];
        };
        /**
         * ContractType
         * @enum {string}
         */
        ContractType: "CLT" | "PJ" | "INTERNSHIP" | "APPRENTICE" | "TEMPORARY" | "CONTRACTOR" | "OTHER";
        /** EducationInput */
        EducationInput: {
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
            /** Course */
            course: string;
            /** Degree Type */
            degree_type?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Institution */
            institution: string;
            /** Source Ref */
            source_ref?: string | null;
            /** @default USER_CONFIRMED */
            source_type: components["schemas"]["FactSource"];
            /** Start Date */
            start_date?: string | null;
            status: components["schemas"]["EducationStatus"];
        };
        /** EducationResponse */
        EducationResponse: {
            /** Confidence */
            confidence: number;
            /** Confirmed At */
            confirmed_at: string | null;
            /** Course */
            course: string;
            /** Degree Type */
            degree_type: string | null;
            /** End Date */
            end_date: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Institution */
            institution: string;
            /** Source Ref */
            source_ref: string | null;
            source_type: components["schemas"]["FactSource"];
            /** Start Date */
            start_date: string | null;
            status: components["schemas"]["EducationStatus"];
        };
        /**
         * EducationStatus
         * @enum {string}
         */
        EducationStatus: "IN_PROGRESS" | "COMPLETED" | "PAUSED" | "DROPPED";
        /**
         * EvaluationErrorCategory
         * @enum {string}
         */
        EvaluationErrorCategory: "MISSING_PROFILE_EVIDENCE" | "BAD_JOB_NORMALIZATION" | "SIMPLE_ALIAS" | "SEMANTIC_EQUIVALENCE" | "PREFERENCE_RULE" | "COVERAGE_FAILURE" | "RANKING_WEIGHT" | "OTHER";
        /** ExperienceInput */
        ExperienceInput: {
            /** Company Name */
            company_name: string;
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
            /** Description */
            description?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Facts */
            facts?: components["schemas"]["CandidateFactInput"][];
            /**
             * Is Current
             * @default false
             */
            is_current: boolean;
            /** Location */
            location?: string | null;
            /** Role Title */
            role_title: string;
            /** Source Ref */
            source_ref?: string | null;
            /** @default USER_CONFIRMED */
            source_type: components["schemas"]["FactSource"];
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
        };
        /** ExperienceResponse */
        ExperienceResponse: {
            /** Company Name */
            company_name: string;
            /** Confidence */
            confidence: number;
            /** Confirmed At */
            confirmed_at: string | null;
            /** Description */
            description: string | null;
            /** End Date */
            end_date: string | null;
            /** Facts */
            facts: components["schemas"]["CandidateFactResponse"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Current */
            is_current: boolean;
            /** Location */
            location: string | null;
            /** Role Title */
            role_title: string;
            /** Source Ref */
            source_ref: string | null;
            source_type: components["schemas"]["FactSource"];
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
        };
        /**
         * FactKind
         * @enum {string}
         */
        FactKind: "RESPONSIBILITY" | "ACHIEVEMENT" | "TOOL" | "DOMAIN" | "PROJECT" | "OTHER";
        /**
         * FactSource
         * @enum {string}
         */
        FactSource: "USER_CONFIRMED" | "RESUME_EXTRACTED" | "ATS_IMPORTED" | "AI_DRAFT" | "SYSTEM_INFERRED";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** JobMatchResponse */
        JobMatchResponse: {
            band: components["schemas"]["MatchBand"];
            /** Evaluation Coverage */
            evaluation_coverage: number;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Matched Preferred */
            matched_preferred: number;
            /** Matched Required */
            matched_required: number;
            /** Missing Preferred */
            missing_preferred: number;
            /** Missing Required */
            missing_required: number;
            opportunity_compatibility?: components["schemas"]["OpportunityCompatibilityResponse"] | null;
            /** Preference Results */
            preference_results: components["schemas"]["PreferenceMatchResponse"][];
            /** Preference Score */
            preference_score: number | null;
            professional_fit?: components["schemas"]["ProfessionalFitResponse"] | null;
            /**
             * Profile Id
             * Format: uuid
             */
            profile_id: string;
            /** Requirement Results */
            requirement_results: components["schemas"]["RequirementMatchResponse"][];
            /** Requirement Score */
            requirement_score: number | null;
            /** Score */
            score: number | null;
            /** Unknown Requirements */
            unknown_requirements: number;
            /** Warnings */
            warnings: string[];
        };
        /** JobPostingResponse */
        JobPostingResponse: {
            /** Apply Url */
            apply_url: string | null;
            /** City */
            city: string | null;
            /** Company Name */
            company_name: string;
            contract_type: components["schemas"]["ContractType"] | null;
            /** Country Code */
            country_code: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description Raw */
            description_raw: string;
            /** External Id */
            external_id: string | null;
            /** Fingerprint */
            fingerprint: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Location Text */
            location_text: string | null;
            /** Published At */
            published_at: string | null;
            /** Requirements */
            requirements: components["schemas"]["JobRequirementResponse"][];
            /** Salary Currency */
            salary_currency: string;
            /** Salary Max */
            salary_max: number | null;
            /** Salary Min */
            salary_min: number | null;
            salary_period: components["schemas"]["SalaryPeriod"] | null;
            seniority: components["schemas"]["Seniority"] | null;
            source_kind: components["schemas"]["JobSourceKind"];
            /** Source Platform */
            source_platform: string | null;
            /** Source Url */
            source_url: string | null;
            /** State */
            state: string | null;
            status: components["schemas"]["JobStatus"];
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Valid Through */
            valid_through: string | null;
            work_model: components["schemas"]["WorkModel"] | null;
        };
        /** JobPostingUpsert */
        JobPostingUpsert: {
            /** Apply Url */
            apply_url?: string | null;
            /** City */
            city?: string | null;
            /** Company Name */
            company_name: string;
            contract_type?: components["schemas"]["ContractType"] | null;
            /**
             * Country Code
             * @default BR
             */
            country_code: string;
            /** Description Raw */
            description_raw: string;
            /** External Id */
            external_id?: string | null;
            /** Location Text */
            location_text?: string | null;
            /** Published At */
            published_at?: string | null;
            /** Requirements */
            requirements?: components["schemas"]["JobRequirementInput"][];
            /**
             * Salary Currency
             * @default BRL
             */
            salary_currency: string;
            /** Salary Max */
            salary_max?: number | null;
            /** Salary Min */
            salary_min?: number | null;
            salary_period?: components["schemas"]["SalaryPeriod"] | null;
            seniority?: components["schemas"]["Seniority"] | null;
            /** @default MANUAL */
            source_kind: components["schemas"]["JobSourceKind"];
            /** Source Platform */
            source_platform?: string | null;
            /** Source Url */
            source_url?: string | null;
            /** State */
            state?: string | null;
            /** @default ACTIVE */
            status: components["schemas"]["JobStatus"];
            /** Title */
            title: string;
            /** Valid Through */
            valid_through?: string | null;
            work_model?: components["schemas"]["WorkModel"] | null;
        };
        /** JobRequirementInput */
        JobRequirementInput: {
            /** Context Qualifier */
            context_qualifier?: string | null;
            /** @default REQUIRED */
            importance: components["schemas"]["RequirementImportance"];
            kind: components["schemas"]["RequirementKind"];
            /** Min Years */
            min_years?: number | null;
            required_education_status?: components["schemas"]["EducationStatus"] | null;
            required_language_proficiency?: components["schemas"]["LanguageProficiency"] | null;
            required_level?: components["schemas"]["SkillLevel"] | null;
            /** Source Text */
            source_text?: string | null;
            /** Value */
            value: string;
        };
        /** JobRequirementResponse */
        JobRequirementResponse: {
            /** Context Qualifier */
            context_qualifier: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            importance: components["schemas"]["RequirementImportance"];
            kind: components["schemas"]["RequirementKind"];
            /** Min Years */
            min_years: number | null;
            /** Normalized Value */
            normalized_value: string;
            /** Ordinal */
            ordinal: number;
            required_education_status: components["schemas"]["EducationStatus"] | null;
            required_language_proficiency: components["schemas"]["LanguageProficiency"] | null;
            required_level: components["schemas"]["SkillLevel"] | null;
            /** Source Text */
            source_text: string | null;
            /** Value */
            value: string;
        };
        /**
         * JobSourceKind
         * @enum {string}
         */
        JobSourceKind: "MANUAL" | "ATS" | "JOB_BOARD" | "COMPANY_SITE" | "OTHER";
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "ACTIVE" | "CLOSED" | "ARCHIVED";
        /** JobSummaryResponse */
        JobSummaryResponse: {
            /** Company Name */
            company_name: string;
            contract_type: components["schemas"]["ContractType"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Location Text */
            location_text: string | null;
            /** Requirement Count */
            requirement_count: number;
            seniority: components["schemas"]["Seniority"] | null;
            /** Source Platform */
            source_platform: string | null;
            status: components["schemas"]["JobStatus"];
            /** Title */
            title: string;
            work_model: components["schemas"]["WorkModel"] | null;
        };
        /** LanguageInput */
        LanguageInput: {
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
            /** Name */
            name: string;
            proficiency: components["schemas"]["LanguageProficiency"];
            /** Source Ref */
            source_ref?: string | null;
            /** @default USER_CONFIRMED */
            source_type: components["schemas"]["FactSource"];
        };
        /**
         * LanguageProficiency
         * @enum {string}
         */
        LanguageProficiency: "BASIC" | "ELEMENTARY" | "INTERMEDIATE" | "UPPER_INTERMEDIATE" | "ADVANCED" | "FLUENT" | "NATIVE";
        /** LanguageResponse */
        LanguageResponse: {
            /** Confidence */
            confidence: number;
            /** Confirmed At */
            confirmed_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            proficiency: components["schemas"]["LanguageProficiency"];
            /** Source Ref */
            source_ref: string | null;
            source_type: components["schemas"]["FactSource"];
        };
        /**
         * MatchBand
         * @enum {string}
         */
        MatchBand: "STRONG" | "GOOD" | "PARTIAL" | "LOW" | "INSUFFICIENT_DATA";
        /** MatchEvidenceResponse */
        MatchEvidenceResponse: {
            /** Detail */
            detail?: string | null;
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /** Entity Type */
            entity_type: string;
            source_type: components["schemas"]["FactSource"];
            /** Value */
            value: string;
        };
        /** OpportunityCompatibilityResponse */
        OpportunityCompatibilityResponse: {
            /** Blocked */
            blocked: boolean;
            /** Blockers */
            blockers: components["schemas"]["PreferenceAspect"][];
            /** Coverage */
            coverage: number;
            /** Score */
            score: number | null;
        };
        /** PilotEvalMetricsResponse */
        PilotEvalMetricsResponse: {
            /** Average Coverage */
            average_coverage: number;
            /** Ndcg At 10 */
            ndcg_at_10: number;
            /** Ndcg At 5 */
            ndcg_at_5: number;
            /** Recall At 10 */
            recall_at_10: number;
            /** Recall At 5 */
            recall_at_5: number;
            /** Relevant Count */
            relevant_count: number;
            /** Sample Count */
            sample_count: number;
            /** Scored Count */
            scored_count: number;
        };
        /** PilotEvalRankingItemResponse */
        PilotEvalRankingItemResponse: {
            /** Apply Intent */
            apply_intent: number | null;
            /** Band */
            band: string;
            /** Blocker Real */
            blocker_real: boolean;
            /** Company Name */
            company_name: string;
            /** Coverage */
            coverage: number;
            error_category: components["schemas"]["EvaluationErrorCategory"] | null;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Reason */
            reason: string | null;
            /** Relevance */
            relevance: number;
            /** Score */
            score: number | null;
            /** Title */
            title: string;
        };
        /** PilotEvalReportResponse */
        PilotEvalReportResponse: {
            metrics: components["schemas"]["PilotEvalMetricsResponse"];
            /** Ranking */
            ranking: components["schemas"]["PilotEvalRankingItemResponse"][];
        };
        /** PilotEvaluationResponse */
        PilotEvaluationResponse: {
            /** Apply Intent */
            apply_intent: number | null;
            /** Blocker Real */
            blocker_real: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            error_category: components["schemas"]["EvaluationErrorCategory"] | null;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Reason */
            reason: string | null;
            /** Relevance */
            relevance: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PilotEvaluationUpsert */
        PilotEvaluationUpsert: {
            /** Apply Intent */
            apply_intent?: number | null;
            /**
             * Blocker Real
             * @default false
             */
            blocker_real: boolean;
            error_category?: components["schemas"]["EvaluationErrorCategory"] | null;
            /** Reason */
            reason?: string | null;
            /** Relevance */
            relevance: number;
        };
        /** PilotReviewJobResponse */
        PilotReviewJobResponse: {
            /** Company Name */
            company_name: string;
            /** Contract Type */
            contract_type: string | null;
            evaluation: components["schemas"]["PilotEvaluationResponse"] | null;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Location Text */
            location_text: string | null;
            /** Requirement Count */
            requirement_count: number;
            /** Seniority */
            seniority: string | null;
            /** Title */
            title: string;
            /** Work Model */
            work_model: string | null;
        };
        /**
         * PreferenceAspect
         * @enum {string}
         */
        PreferenceAspect: "TITLE" | "LOCATION" | "WORK_MODEL" | "CONTRACT_TYPE" | "SENIORITY" | "SALARY";
        /** PreferenceMatchResponse */
        PreferenceMatchResponse: {
            aspect: components["schemas"]["PreferenceAspect"];
            /** Candidate Value */
            candidate_value: string[];
            /** Job Value */
            job_value: string[];
            /** Reason */
            reason: string;
            status: components["schemas"]["PreferenceMatchStatus"];
        };
        /**
         * PreferenceMatchStatus
         * @enum {string}
         */
        PreferenceMatchStatus: "ALIGNED" | "CONFLICT" | "UNKNOWN";
        /** ProfessionalFitResponse */
        ProfessionalFitResponse: {
            band: components["schemas"]["MatchBand"];
            /** Confidence */
            confidence: number;
            /** Score */
            score: number | null;
        };
        /**
         * RequirementImportance
         * @enum {string}
         */
        RequirementImportance: "REQUIRED" | "PREFERRED" | "INFO";
        /**
         * RequirementKind
         * @enum {string}
         */
        RequirementKind: "SKILL" | "EXPERIENCE" | "EDUCATION" | "LANGUAGE" | "CERTIFICATION" | "LOCATION" | "WORK_MODEL" | "CONTRACT" | "DOMAIN" | "TOOL" | "RESPONSIBILITY" | "OTHER";
        /** RequirementMatchResponse */
        RequirementMatchResponse: {
            /** Evidence */
            evidence: components["schemas"]["MatchEvidenceResponse"][];
            importance: components["schemas"]["RequirementImportance"];
            kind: components["schemas"]["RequirementKind"];
            /** Reason */
            reason: string;
            /**
             * Requirement Id
             * Format: uuid
             */
            requirement_id: string;
            status: components["schemas"]["RequirementMatchStatus"];
            /** Value */
            value: string;
            /** Weight */
            weight: number;
        };
        /**
         * RequirementMatchStatus
         * @enum {string}
         */
        RequirementMatchStatus: "MATCHED" | "GAP" | "UNKNOWN" | "INFO";
        /**
         * SalaryPeriod
         * @enum {string}
         */
        SalaryPeriod: "HOUR" | "DAY" | "MONTH" | "YEAR" | "OTHER";
        /**
         * Seniority
         * @enum {string}
         */
        Seniority: "INTERN" | "TRAINEE" | "JUNIOR" | "MID" | "SENIOR" | "SPECIALIST" | "LEAD" | "MANAGER" | "DIRECTOR" | "EXECUTIVE";
        /** SkillInput */
        SkillInput: {
            /** Category */
            category?: string | null;
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
            level?: components["schemas"]["SkillLevel"] | null;
            /** Name */
            name: string;
            /** Source Ref */
            source_ref?: string | null;
            /** @default USER_CONFIRMED */
            source_type: components["schemas"]["FactSource"];
            /** Years Experience */
            years_experience?: number | null;
        };
        /**
         * SkillLevel
         * @enum {string}
         */
        SkillLevel: "BEGINNER" | "INTERMEDIATE" | "ADVANCED" | "EXPERT";
        /** SkillResponse */
        SkillResponse: {
            /** Category */
            category: string | null;
            /** Confidence */
            confidence: number;
            /** Confirmed At */
            confirmed_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            level: components["schemas"]["SkillLevel"] | null;
            /** Name */
            name: string;
            /** Source Ref */
            source_ref: string | null;
            source_type: components["schemas"]["FactSource"];
            /** Years Experience */
            years_experience: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WorkModel
         * @enum {string}
         */
        WorkModel: "REMOTE" | "HYBRID" | "ONSITE";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_review_jobs_api_v1_evals_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PilotReviewJobResponse"][];
                };
            };
        };
    };
    replace_job_evaluation_api_v1_evals_jobs__job_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PilotEvaluationUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PilotEvaluationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_eval_report_api_v1_evals_report_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PilotEvalReportResponse"];
                };
            };
        };
    };
    read_jobs_api_v1_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSummaryResponse"][];
                };
            };
        };
    };
    create_job_api_v1_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobPostingUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPostingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPostingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_job_api_v1_jobs__job_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobPostingUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPostingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_job_match_api_v1_jobs__job_id__match_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobMatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_profile_api_v1_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateProfileResponse"];
                };
            };
        };
    };
    upsert_profile_api_v1_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidateProfileUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    liveness_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
